name: Descargar datos SMN

on:
  workflow_dispatch:  # permite correr manualmente
  schedule:
    - cron: "0 03 * * *"  # todos los días a las 03:00 AM UTC

jobs:
  descargar_clima:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar librerías necesarias
        run: |
          R -e 'install.packages(c("readr","dplyr","lubridate"))'

      - name: Ejecutar script de descarga
        run: Rscript scripts/descarga_clima_smn.R

      - name: Commit y push del CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add clima_smn_horarios.csv
          git commit -m "Actualización diaria de datos SMN [skip ci]" || echo "No hay cambios"
          git push
